version: '3.8'

services:
  reflourish-app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/packages.db:/app/packages.db
      - ./backend/users.db:/app/users.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
