[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[phases.build]
cmds = ["echo 'Build phase - no build needed for Python Flask app'"]

[start]
cmd = "cd backend && python app.py"
