[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && python app.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[environments.production]
DATABASE_URL = "sqlite:///app/backend/packages.db"
FLASK_ENV = "production"
